Repository povel62/cpsc455-project, pull requests merged in 2021-06, with the labels that each got.

#11 Adding prettier, eslint, react router, redux and materail ui
  .eslintrc.json
  README.md
  client/.eslintrc.js
  client/.eslintrc.json
  client/package.json
  client/src/App.js
  client/src/App.test.js
  client/src/components/Home/index.js
  client/src/index.js
  client/src/redux/actions/actionTypes.js
  client/src/redux/actions/actions.js
  client/src/redux/configureStore.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/reducer.js
  client/src/reportWebVitals.js
  client/src/setupTests.js
  client/yarn.lock
  package.json
  yarn.lock
Labels: documentation, enhancement, good first issue

#12 Adding jwt and signup plus login api
  README.md
  controllers/member-ctrl.js
  controllers/user-ctrl.js
  models/member-model.js
  models/user-model.js
  package-lock.json
  package.json
  routes/member-router.js
  routes/user-router.js
  server.js
  yarn.lock
Labels: enhancement

#15 Adding pretteier and eslint fixes
  .eslintrc.js
  controllers/user-ctrl.js
  models/user-model.js
  package.json
  routes/user-router.js
  server.js
  yarn.lock
Labels: enhancement

#17 Add kaggle api to account model with encryption, add kaggle actions definitions, modify eslint rules
  .eslintrc.js
  controllers/kaggle-ctrl.js
  controllers/user-ctrl.js
  models/user-model.js
  routes/kaggle-router.js
  server.js
  util/security.js
Labels: enhancement

#21 Feature/guest + bug fix + readme change
  README.md
  controllers/user-ctrl.js
  models/user-model.js
  routes/user-router.js
  util/security.js
  util/validation.js
Labels: bug, enhancement

#35 Adding jobs model and its respective apis
  controllers/generic-ctrl.js
  controllers/job-ctrl.js
  controllers/user-ctrl.js
  models/job-model.js
  models/user-model.js
  package.json
  routes/job-router.js
  routes/user-router.js
  server.js
  util/security.js
  yarn.lock
Labels: enhancement

#40 Adding signup changes
  client/yarn.lock
  controllers/user-ctrl.js
Labels: enhancement

#42 change jobs model and apis
  controllers/job-ctrl.js
  models/job-model.js
  routes/job-router.js
Labels: enhancement

#45 Refactoring ui look and feel
  client/package.json
  client/src/App.js
  client/src/background-images/ml1.png
  client/src/background-images/ml10.png
  client/src/background-images/ml2.png
  client/src/background-images/ml3.png
  client/src/background-images/ml4.png
  client/src/background-images/ml5.png
  client/src/background-images/ml6.png
  client/src/background-images/ml7.png
  client/src/background-images/ml8.png
  client/src/background-images/ml9.png
  client/src/components/Login/Login.js
  client/src/components/Navigation/Navigation.js
  client/src/components/Signin/Signin.js
  client/src/components/Signup/Signup.js
  client/src/index.css
  client/src/index.js
  client/src/redux/actions/actions.js
  client/src/redux/configureStore.js
  client/src/redux/reducers/loginReducer.js
  client/src/router/AuthRoute.js
  client/yarn.lock
  controllers/user-ctrl.js
  package.json
Labels: enhancement

#46 FInished work on frontend styling
  client/src/App.js
  client/src/api/UserService.js
  client/src/components/Faq/Faq.js
  client/src/components/Navigation/Navigation.js
  client/src/components/Signin/Signin.js
  client/src/components/Signup/Signup.js
  controllers/job-ctrl.js
  controllers/user-ctrl.js
  server.js
Labels: enhancement

#47 Feature/kaggle frontend partial
  .gitignore
  client/package.json
  client/src/components/KaggleDashboard/KaggleActionPane.js
  client/src/components/KaggleDashboard/KaggleDashboard.css
  client/src/components/KaggleDashboard/KaggleDashboard.js
  client/src/components/KaggleDashboard/KaggleDataEntry.js
  client/src/components/KaggleDashboard/KaggleDataPane.js
  client/src/components/KaggleDashboard/KaggleFacade.js
  client/src/components/KaggleDashboard/KaggleListEntry.js
  client/src/components/KaggleDashboard/KaggleSearchPane.js
  client/src/components/KaggleDashboard/kaggleApi.js
  client/src/components/Navigation/Navigation.js
  client/src/redux/actions/actions.js
  client/src/redux/reducers/kaggleReducer.js
  client/src/redux/reducers/rootReducer.js
  client/yarn.lock
  controllers/generic-ctrl.js
  controllers/kaggle-ctrl.js
  package.json
  requirements.txt
  routes/kaggle-router.js
  server.js
  util/kaggleWrapper.py
  yarn.lock
Labels: enhancement

#50 add axios
  client/src/components/KaggleDashboard/KaggleActionPane.js
  controllers/job-ctrl.js
  controllers/kaggle-ctrl.js
  models/job-model.js
  package.json
  routes/job-router.js
  routes/kaggle-router.js
  yarn.lock
Labels: bug

#51 Merge tutorial with account dashboard
  client/package.json
  client/src/components/AccountDashboard/AccountDashboard.js
  client/src/components/Navigation/Navigation.js
  client/src/components/Tutorial/Tutorial.css
  client/src/components/Tutorial/Tutorial.js
  client/src/index.js
  client/yarn.lock
Labels: enhancement

#52 Feature/kaggle frontend
  client/src/components/KaggleDashboard/KaggleActionPane.js
  client/src/components/KaggleDashboard/KaggleListEntry.js
  controllers/kaggle-ctrl.js
  package.json
  routes/kaggle-router.js
  yarn.lock
Labels: enhancement

#53 Merge Staging into main
  client/package.json
  client/src/App.js
  client/src/components/AccountDashboard/AccountDashboard.css
  client/src/components/AccountDashboard/AccountDashboard.js
  client/src/components/ControlDashboard/ControlDashboard.css
  client/src/components/ControlDashboard/ControlDashboard.js
  client/src/components/ControlDashboard/Row.js
  client/src/components/ControlDashboard/rowStyles.js
  client/src/components/Faq/Faq.js
  client/src/components/Instructions/Instructions.css
  client/src/components/Instructions/Instructions.js
  client/src/components/Login/Login.js
  client/src/components/Navigation/Navigation.js
  client/src/components/Signup/Signup.css
  client/src/components/Signup/Signup.js
  client/src/components/Tutorial/Tutorial.css
  client/src/components/Tutorial/Tutorial.js
  client/yarn.lock
  controllers/user-ctrl.js
  package.json
  routes/user-router.js
  yarn.lock
Labels: enhancement

#54 bug fix
  package.json
  yarn.lock
Labels: bug
